CREATE TABLE Clientes (
   Id INT PRIMARY KEY IDENTITY(1,1),
   Nome VARCHAR(100) NOT NULL,
   CNPJ VARCHAR(14) NOT NULL UNIQUE,
   DataCadastro DATE NOT NULL,
   Endereco VARCHAR(100) NOT NULL,
   Telefone VARCHAR(20) NOT NULL
);